### PR TITLE
more from faqs

### PR DESCRIPTION
**Pull request by BambooSphere**

### CODE REVIEW

**Comment by hillbicks** [comment]
the general.md file seems to be empty, can you check that please?

**Comment by dmitry-naumovich** [comment]
Sorry, I'll be able to check that in some hours.

**Comment by BambooSphere** [comment]
thats weird. on my computer it's there and i see the changes in the commits. but somehow it's not being transmitted during the pull-request. will look into it later... but weird

**Comment by hillbicks** [comment]
that's not your pull request dmitry, this one is for bamboosphere. :)

**Comment by BambooSphere** [comment]
hey, i think it's ok. you have to click on expand to see the whole window. it just shows the first few lines of the commit unless you expand...

**Comment by hillbicks** [comment]
D'OH. You're right, didn't see that.

**Pull request merged**
